name: "dbt_macro_as_packages"
version: "0.1.0"

require-dbt-version: ">=1.1.0"
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"